//PROPERTIES OF A DP
//* THE OPTIMAL SUBTREE: FOR SOLVING THE BIGGER PROBLEM SMALLER PROBLEM IS REQUIRED[DEPENDS]
//*OVERLAPPING SUBPROBLEM [IF SOMETHING REPEAT AGAIN IN A PROBLEM USE THE PAST EXP] [FIBONACCI]

//OVERLAPPINF SUBPROBLEM CAN BE SOLVED USING TWO THINGS : MEMOISATION() AND TABULATION
//MEMOISATION IS MAKING A TABLE THAT WILL CHECK EVERYTIME THAT THE IT HAD BEEN COMPUTED EARLIER 
// MEMOISATION IS OFTEN CALLED TOP-BOTTOM 

//TABULATION IS CALLED BOTTOM UP METHOD AND WRITE EVERYTINH FROM BASE

//PROBLEMS : FIND THE NUMBER OF WAYS, RECERRENCE RELATION ,MAXIMISATION AND MIM PROBLEM

//OVERLAPPING SUBPROBLEM RRECURRENCE RELATION
#include<bits/stdc++.h>

using namespace std;

int main()
{

    return 0;
}






